2024-11-22T09:03:01.500Z - Sync Error: ReferenceError: sheets is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:81:22)
    at Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:177:9)
    at Task.execute (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\task.js:17:25)
    at ScheduledTask.now (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:38:33)
    at Scheduler.<anonymous> (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:25:18)
    at Scheduler.emit (node:events:519:28)
    at Timeout.matchTime [as _onTimeout] (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduler.js:30:26)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
2024-11-22T09:04:01.999Z - Sync Error: ReferenceError: sheets is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:81:22)
    at Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:177:9)
    at Task.execute (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\task.js:17:25)
    at ScheduledTask.now (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:38:33)
    at Scheduler.<anonymous> (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:25:18)
    at Scheduler.emit (node:events:519:28)
    at Timeout.matchTime [as _onTimeout] (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduler.js:30:26)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
2024-11-22T09:05:01.487Z - Sync Error: ReferenceError: sheets is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:81:22)
    at Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:177:9)
    at Task.execute (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\task.js:17:25)
    at ScheduledTask.now (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:38:33)
    at Scheduler.<anonymous> (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:25:18)
    at Scheduler.emit (node:events:519:28)
    at Timeout.matchTime [as _onTimeout] (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduler.js:30:26)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
2024-11-22T09:06:01.078Z - Sync Error: ReferenceError: sheets is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:81:22)
    at Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:177:9)
    at Task.execute (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\task.js:17:25)
    at ScheduledTask.now (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:38:33)
    at Scheduler.<anonymous> (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduled-task.js:25:18)
    at Scheduler.emit (node:events:519:28)
    at Timeout.matchTime [as _onTimeout] (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\node_modules\node-cron\src\scheduler.js:30:26)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
2024-11-22T10:42:01.770Z - Sync Error: ReferenceError: rows is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:128:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:202:3)
2024-11-22T10:42:06.368Z - Sync Error: ReferenceError: rows is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:128:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:202:3)
2024-11-22T10:45:46.435Z - Sync Error: ReferenceError: successCount is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:229:78)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:244:3)
2024-11-22T11:04:21.411Z - Sync Error: ReferenceError: successCount is not defined
    at syncFeedbackData (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:227:78)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task._execution (C:\Users\nithi\OneDrive\Documents\copy of project\menew\backend\server.js:242:3)
